### ISSUE TITLE
prs for visual changes?

### ISSUE THREAD

**Issue by hmig** [visualregressiontesting/visualregressiontesting.com#1]
Hi,

The border around the different sections was driving me nuts because it sticks out 1px from the h2's (http://screencast.com/t/ZOMCafX0S). I messed around and made it look like: http://screencast.com/t/k1XdVK3WM. If you like it, I'll pr it for you.

Thanks!

Heather

**Comment by klamping** [comment]
Now that I see it, I can't unsee it!

A PR with your new styles would be fantastic! Please send it along :)

**Comment by micahgodbolt** [comment]
I fixed the h2 issue, though didn't address any of the other styles. I like the visual approach. If @hmig doesn't get to it first, I might try to create a PR with some new styles based on that screen cap.

**Comment by hmig** [comment]
I'll make the changes now. They were super-simple. ;)
