### ISSUE TITLE
New resource: Wraith article

### ISSUE THREAD

**Issue by theonicolaou** [visualregressiontesting/visualregressiontesting.com#2]
Hi,

Please can you add Wrestling with Wraith: Quick and Dirty Visual Regression Testing (https://www.phase2technology.com/blog/wrestling-with-wraith-quick-and-dirty-visual-regression-testing/), it looks really useful

Cheers

Theo

**Comment by klamping** [comment]
Done, thanks!

https://github.com/visualregressiontesting/visualregressiontesting.com/commit/fac23c558eec3f1944c1de8d30672c5092b807b6

**Comment by micahgodbolt** [comment]
Hah, funny that someone else has to come along to remind me that we have other VRT articles on the phase2 website!
